server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          search-paths: config
          uri: https://github.com/pinggavin/SpringCloudConfig
          username:
          password:


