server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          search-paths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          username:
          password:


