server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          search-paths: cloudconfig
          uri: https://github.com/pinggavin/
          username:
          password:


